# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Despliegue de aplicacion DePeis backend

on:
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:
  build:

    #runs-on: ubuntu-latest  # Crea un contenedor docker en el servidor remoto
    runs-on: self-hosted  # Ejecuta Node como si estuviera en local.

    strategy:
      matrix:
        #node-version: [14.x, 16.x, 18.x]
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm i
    # - run: npm start >> logfile.txt 2>&1 &
    - run: npm start
    
      env: # Or as an environment variable
        MONGOUSER: ${{ secrets.MONGOUSER }}
        MONGOKEY: ${{ secrets.MONGOKEY }}
        CLOUSTERNAME: ${{ secrets.CLOUSTERNAME }}
        DBNAME: ${{ secrets.DBNAME }}
        PORT: ${{ secrets.PORT }}

    - name: Post Start Stop
      run: |
        echo "Post start step ejecuted successfuly"

    #- run: npm run build --if-present
    #- run: npm test
